server:
  port: 8080



info:
  app:
    id: 2020.02.11
    version: 1.0.0

management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
