server:
  port: 8080
#  servlet:
#    context-path: /demo
# 若要访问端点信息，需要配置用户名和密码
#spring:
#  security:
    #user:
      #name: aa
      #password: 123456
management:
  # 端点信息接口使用的端口，为了和主系统接口使用的端口进行分离
  #server:
    #port: 8090
    #servlet:
      #context-path: /sys
  # 端点健康情况，默认值"never"，设置为"always"可以显示硬盘使用情况和线程情况
  endpoint:
    health:
      show-details: always
  # 设置端点暴露的哪些内容，默认["health","info"]，设置"*"代表暴露所有可访问的端点
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    id: 2020.02.11
    version: 1.0.0


